### 계좌 등록
# curl -XPOST -H "Content-Type: application/json"
#  -d '{"id": 1, “number”: “1000-1000”, “balance”: 10000}'
#  http://localhost:8080/accounts
POST http://localhost:8080/accounts
Content-Type: application/json

{
  "id": 1,
  "number":"1000-1000",
  "balance": 10000
}

### 계좌 전체 조회
# curl -X GET http://localhost:8080/accounts
GET http://localhost:8080/accounts

### 계좌 조회
# curl -X GET http://localhost:8080/accounts/1
GET http://localhost:8080/accounts/1

### 계좌 삭제
# curl -X DELETE http://localhost:8080/accounts/1
DELETE http://localhost:8080/accounts/1